# Define the default driver
#webdriver.driver=phantomjs

# Appears at the top of the reports
# Capturas automáticas durante la ejecución
serenity.take.screenshots = AFTER_EACH_STEP
# serenity.take.screenshots = FOR_FAILURES
# serenity.take.screenshots = BEFORE_AND_AFTER_EACH_STEP

serenity.project.name = Demo Project Appium, Serenity Screenplay and Cucumber

# Root package for any JUnit acceptance tests
#serenity.test.root=net.serenitybdd.tutorials.features

# Customise your riequirements hierarchy
#serenity.requirement.types=feature, story

# Run the tests without calling webdriver - useful to check your JUnit wiring
#serenity.dry.run=true

# Customise browser size
#serenity.browser.height = 1200
#serenity.browser.width = 1200

webdriver.driver= appium
#webdriver.timeouts.implicitlywait = 50000
#webdriver.wait.for.timeout = 100000

appium.hub = http://localhost:4723/wd/hub

####### Android CAPS ######
appium.automationName=UIAutomator2
appium.platformName = android
appium.platformVersion = 16.0
browserName=Chrome
appium.deviceName  = android
#chromedriverExecutable= C:/Users/cerh2/Desktop/webdriver-mobile/chromedriver.exe
#appium.app =  https://github.com/jdmesalosada/appium-app-to-practice/raw/master/TheApp-v1.10.0.apk
appium.app = C:/Users/cerh2/Desktop/Appium/Appium-Apk_base/src/test/resources/TheApp.apk

appium.newCommandTimeout = 1000